add tagger verify step

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -22,20 +22,28 @@ jobs:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v4
-    - name: Check tag version
+    # - name: Verify tag and file verison match
+    #   run: |
+    #     TAG=${{ github.ref }}
+    #     TAG_NAME="${TAG#refs/tags/}"
+    #     echo "tag version is " $TAG_NAME
+    #     file_version=v$(.circleci/version.sh)
+    #     echo "file version is " $file_version
+    #     if [ $file_version == ${TAG_NAME%-*} ]; then
+    #       echo "verification pass"
+    #     else
+    #       echo "It's not same version."
+    #       exit 1
+    #     fi
+    - name: Verify tag and file verison match
       run: |
-        TAG=${{ github.ref }}
-        TAG_NAME="${TAG#refs/tags/}"
-        echo "tag version is " $TAG_NAME
-        file_version=v$(.circleci/version.sh)
-        echo "file version is " $file_version
-        if [ $file_version == ${CIRCLE_TAG%-*} ]; then
-          echo "verification pass"
+        TAGGER=$(git for-each-ref --format='%(tagger)' refs/tags/$CIRCLE_TAG | sed 's/ .*//')
+        if [ $TAGGER == 'circleci-klaytn' ]; then
+          echo "Pass! Tagger is circleci-klaytn"
         else
-          echo "It's not same version."
+          echo "only circleci-klaytn can tagging major version"
           exit 1
         fi
-
   # docs_test:
   #   runs-on: ubuntu-latest
   #   steps:
